openapi: 3.0.0
info:
  title: API Pix
  version: "2.6.2"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Suporte PIX BCB
    email: suporte.pix@bcb.gov.br
    url: https://www.bcb.gov.br/estabilidadefinanceira/pix
  description: |-
    A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix,
    como criação de cobrança, verificação de Pix recebidos, devolução e consultas.
    Os serviços expostos pelo PSP recebedor permitem ao usuário recebedor estabelecer integração
    de sua automação com os serviços Pix do PSP.

    # Evolução da API Pix

    A API Pix busca respeitar __[SemVer](https://semver.org/lang/pt-BR/)__. Nesse sentido,
    mudanças compatíveis não devem gerar nova versão _major_.

    A versão da API é composta por 4 elementos: _major_, _minor_, _patch_ e _release candidate_.
    A versão `v[x]`que consta no path da URL é o elemento _major_ da versão da API.
    A evolução da versão se dá seguinte forma:

      - Major: alterações incompatíveis, com quebra de contrato (v1.0.0 → v2.0.0)
      - Minor: alterações compatíveis, sem quebra de contrato (v1.1.0 → v1.2.0)
      - Patch: bugfixes, esclarecimentos às especificações, sem alterações funcionais (v1.1.1 → v1.1.2)
      - Release candidate: versões de pré-lançamento de qualquer patch futuro, minor ou major (v1.0.0-rc.1 → v1.0.0-rc.22)

    Alterações sem quebra de contrato e esclarecimentos às especificações podem ocorrer a qualquer momento.
    Clientes devem estar preparados para lidar com essas mudanças sem quebrar.

    As seguintes mudanças são esperadas e consideradas retrocompatíveis:

    - Adição de novos recursos na API Pix.
    - Adição de novos parâmetros opcionais a cobranças.
    - Adição de novos campos em respostas da API Pix.
    - Alteração da ordem de campos.
    - Adição de novos elementos em enumerações


    # Tratamento de erros
